"""Add translated_text column to messages table

Revision ID: a160d06c8bf5
Revises: da6e7676340d
Create Date: 2025-01-05 16:24:05.723376

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a160d06c8bf5"
down_revision: Union[str, None] = "da6e7676340d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
